/**
 * Display-only Arabic labels for real folder paths found in Risen 1 archives
 * (verified against a real 2680-file templates-full.pak). Keyed by the exact
 * full path (not just the leaf name) since the same leaf name can appear
 * under different parents. Purely cosmetic — never used for file operations,
 * selection, or the archive's own paths.
 *
 * Deeply-nested developer/test folders with no clear meaning (e.g. names of
 * individual developers under NPC/Test/Testkram_Thorsten) are intentionally
 * left untranslated rather than guessed.
 */
export const RISEN_FOLDER_NAMES_AR: Record<string, string> = {
  Items: "الأغراض",
  "Items/Amulets": "التمائم",
  "Items/AnimalTrophies": "جوائز الصيد",
  "Items/Armor": "الدروع",
  "Items/Carryable": "أغراض قابلة للحمل",
  "Items/Container": "الحاويات",
  "Items/Food": "الطعام",
  "Items/Helmets": "الخوذات",
  "Items/Keys": "المفاتيح",
  "Items/Magic": "السحر",
  "Items/MagicOrbs": "الكرات السحرية",
  "Items/Minerals": "المعادن",
  "Items/Plants": "النباتات",
  "Items/Potions": "الجرعات",
  "Items/Quests": "أغراض المهام",
  "Items/Quests/Titan_Armor_Set": "طقم درع العملاق",
  "Items/Recipes_Alchemy": "وصفات الخيمياء",
  "Items/Recipes_Cooking": "وصفات الطبخ",
  "Items/Recipes_Trophy": "وصفات الجوائز",
  "Items/Rings": "الخواتم",
  "Items/Runes": "الأحجار الرونية",
  "Items/Scrolls": "اللفافات",
  "Items/Shields": "الدروع الواقية",
  "Items/Smithing_broken": "مواد حدادة معطوبة",
  "Items/Smithing_raw": "مواد حدادة خام",
  "Items/Teleports": "بوابات الانتقال",
  "Items/Tools": "الأدوات",
  "Items/Valueable": "أغراض قيّمة",
  "Items/Weapons_Axes": "الفؤوس",
  "Items/Weapons_Bows": "الأقواس",
  "Items/Weapons_Crossbows": "الأقواس المعترضة",
  "Items/Weapons_Staffs": "العصي السحرية",
  "Items/Weapons_Swords": "السيوف",
  "Items/Weapons_System": "نظام الأسلحة",
  "Items/Written": "مواد مكتوبة",
  "Items/z_DailyRoutines": "روتين يومي (اختبار)",

  Lights: "الإضاءة",
  "Lights/DungeonLights": "إضاءة الأقبية",

  Monster: "الوحوش",
  "Monster/Ambient": "وحوش محيطية",
  "Monster/Kapitel 1": "الفصل 1 (وحوش)",
  "Monster/Kapitel 2": "الفصل 2 (وحوش)",
  "Monster/Kapitel 3": "الفصل 3 (وحوش)",
  "Monster/Kapitel 4": "الفصل 4 (وحوش)",
  "Monster/Monster_Heads": "رؤوس الوحوش",
  "Monster/Special": "وحوش خاصة",

  NPC: "الشخصيات",
  "NPC/Don": "شخصيات الدون",
  "NPC/Harbour": "شخصيات الميناء",
  "NPC/Monastery": "شخصيات الدير",
  "NPC/Test": "اختبار (شخصيات)",
  "NPC/World": "شخصيات العالم",
  "NPC/World_Dead": "شخصيات ميتة",
  "NPC/_HumanParts": "أجزاء جسم بشرية",
  "NPC/_HumanParts/Head": "الرأس",

  Navigation: "الملاحة",
  "Navigation/AI_Helpers": "مساعدات الذكاء الاصطناعي",
  "Navigation/Anchors": "نقاط الإرساء",
  "Navigation/AreaZones": "مناطق المساحة",
  "Navigation/CollisionCircles": "دوائر التصادم",
  "Navigation/Freepoints": "نقاط حرة",
  "Navigation/Freepoints/Story_FPs": "نقاط حرة (القصة)",
  "Navigation/NavZones": "مناطق الملاحة",
  "Navigation/Startpoints": "نقاط الانطلاق",

  Objects: "الكائنات",
  "Objects/Events": "أحداث",
  "Objects/Events/Story_Events": "أحداث القصة",
  "Objects/Interacts": "تفاعلات",
  "Objects/Interacts/Interacts_Story": "تفاعلات القصة",
  "Objects/Special": "كائنات خاصة",
  "Objects/Speedtree": "أشجار (Speedtree)",
  "Objects/TriggerScriptZones": "مناطق تفعيل سكربتية",
  "Objects/_Architecture": "عناصر معمارية",
  "Objects/_Architecture/SpecialStuff": "عناصر معمارية خاصة",
  "Objects/_MultiTemplates": "قوالب متعددة",

  SFX: "المؤثرات الصوتية",
  "SFX/Ambient": "أصوات محيطية",
  "SFX/Entity": "أصوات الكيانات",
  "SFX/Events": "أصوات الأحداث",

  VFX: "التأثيرات البصرية",
  "VFX/Billboards": "لوحات عرض مسطّحة",
  "VFX/Decals": "ملصقات سطحية",
  "VFX/EffectTest": "اختبار تأثيرات",
  "VFX/Emitter": "باعثات الجسيمات",
  "VFX/Events": "تأثيرات الأحداث",
  "VFX/WaterEmitter": "باعث تأثيرات الماء",

  _Intern: "ملفات داخلية",
  "_Intern/BossFight": "قتال زعيم",
  "_Intern/Essentials": "ملفات أساسية",
  "_Intern/Messages": "رسائل",

  // --- Risen 2 (بنية مجلدات مختلفة تماماً عن Risen 1 — تحققت من templates.pak
  // حقيقي، 2213 قالباً، 120 مسار مجلد فريد). المسارات المشتركة مع Risen 1 أعلاه
  // (Items, Navigation/*, Objects/Interacts, SFX/Ambient, VFX/Decals, _Intern)
  // بنفس المعنى فلم تُكرَّر هنا. ---
  Creatures: "المخلوقات",
  Cutscene: "المشاهد السينمائية",
  Essential: "عناصر أساسية",
  "Essential/Voodoo": "فودو (أساسي)",
  "Essential/_Ships": "السفن (أساسي)",

  "Items/Armor_Body": "دروع الجسم",
  "Items/Armor_Feet": "دروع القدمين",
  "Items/Armor_Head": "دروع الرأس",
  "Items/Armor_Legs": "دروع الساقين",
  "Items/Armor_Story": "دروع (قصة)",
  "Items/Carryables": "أغراض قابلة للحمل",
  "Items/Consume_Booze": "المشروبات",
  "Items/Consume_Food": "الطعام",
  "Items/Consume_Food_Story": "الطعام (قصة)",
  "Items/Consume_Potion": "الجرعات",
  "Items/Consume_Potion_Story": "الجرعات (قصة)",
  "Items/Ingredience_Plant": "مكونات نباتية",
  "Items/Ingredience_Plant_Story": "مكونات نباتية (قصة)",
  "Items/Ingredience_Smith": "مكونات حدادة",
  "Items/Ingredience_Smith_Story": "مكونات حدادة (قصة)",
  "Items/Ingredience_Trophy": "مكونات جوائز الصيد",
  "Items/Ingredience_Trophy_Story": "مكونات جوائز الصيد (قصة)",
  "Items/Jewelry": "المجوهرات",
  "Items/Jewelry_Story": "المجوهرات (قصة)",
  "Items/Keys_Story": "المفاتيح (قصة)",
  "Items/LegendaryItems": "أغراض أسطورية",
  "Items/Misc": "متفرقات",
  "Items/Misc_Story": "متفرقات (قصة)",
  "Items/Monster": "أغراض الوحوش",
  "Items/Recipes": "الوصفات",
  "Items/Valueables": "أغراض قيّمة",
  "Items/Valueables_Story": "أغراض قيّمة (قصة)",
  "Items/Voodoo": "أغراض فودو",
  "Items/Voodoo_Story": "أغراض فودو (قصة)",
  "Items/Weapon_Ammo": "ذخيرة الأسلحة",
  "Items/Weapon_Explosives": "المتفجرات",
  "Items/Weapon_Pierce": "أسلحة الطعن",
  "Items/Weapon_Pierce_Story": "أسلحة الطعن (قصة)",
  "Items/Weapon_Pistol": "المسدسات",
  "Items/Weapon_Pistol_Story": "المسدسات (قصة)",
  "Items/Weapon_Rifle": "البنادق",
  "Items/Weapon_Rifle_Story": "البنادق (قصة)",
  "Items/Weapon_Slash": "أسلحة القطع",
  "Items/Weapon_Slash_Story": "أسلحة القطع (قصة)",
  "Items/Weapon_Throwing": "أسلحة الرمي",
  "Items/Weapon_Throwing_Story": "أسلحة الرمي (قصة)",
  "Items/Weapon_Tricks": "خدع الأسلحة",
  "Items/Weapon_Tricks_Story": "خدع الأسلحة (قصة)",
  "Items/Written_Maps": "الخرائط",
  "Items/Written_Maps_Locations": "مواقع الخرائط",
  "Items/Written_Maps_Story": "الخرائط (قصة)",
  "Items/Written_Story": "مواد مكتوبة (قصة)",

  MiniGames: "الألعاب المصغّرة",
  "MiniGames/Drink": "لعبة الشرب",
  "MiniGames/LockPick": "فتح الأقفال",
  "MiniGames/Shoot": "لعبة الرماية",

  NPCs: "الشخصيات",
  "NPCs/Antigua": "أنتيغوا",
  "NPCs/CrystalFortress": "قلعة الكريستال",
  "NPCs/Dummys": "شخصيات وهمية (اختبار)",
  "NPCs/IsleOfDeath": "جزيرة الموت",
  "NPCs/IsleOfThiefs": "جزيرة اللصوص",
  "NPCs/MaracaiBay": "خليج ماراكاي",
  "NPCs/StormIsland": "جزيرة العاصفة",
  "NPCs/SwordCoast": "ساحل السيف",
  "NPCs/Takarigua": "تاكاريغوا",
  "NPCs/TempleOfWater": "معبد الماء",
  "NPCs/TreasureIsland_DLC2": "جزيرة الكنز (DLC2)",
  "NPCs/_Helper": "شخصيات مساعدة",

  "Navigation/AIZones": "مناطق الذكاء الاصطناعي",
  "Navigation/EndBoss": "الزعيم الأخير",
  "Navigation/TriggerScriptZones": "مناطق تفعيل سكربتية",

  "Objects/Buildings": "المباني",
  "Objects/Cannon": "المدافع",
  "Objects/Climbable": "أسطح قابلة للتسلق",
  "Objects/Decoration": "الديكور",
  "Objects/Destructable": "قابل للتدمير",
  "Objects/Furniture": "الأثاث",
  "Objects/GUI": "واجهة المستخدم",
  "Objects/Interacts/Events": "أحداث التفاعلات",
  "Objects/Interacts/Events/Story": "أحداث التفاعلات (قصة)",
  "Objects/Interacts/GUI": "تفاعلات الواجهة",
  "Objects/Interacts/Story": "تفاعلات (قصة)",
  "Objects/Light Sources": "مصادر الإضاءة",
  "Objects/Misc": "متفرقات",
  "Objects/Nature": "الطبيعة",
  "Objects/River": "الأنهار",
  "Objects/Ship Stuff": "أغراض السفن",
  "Objects/Speedtrees": "أشجار (Speedtree)",
  "Objects/Streets": "الطرقات",
  "Objects/Traps": "الفخاخ",
  "Objects/_Prefabs": "قوالب جاهزة",

  "VFX/Animations": "الرسوم المتحركة",
  "VFX/Creatures": "تأثيرات المخلوقات",
  "VFX/Cutscenes": "تأثيرات المشاهد السينمائية",
  "VFX/Environment": "تأثيرات البيئة",
  "VFX/Flocking": "حركة الأسراب",
  "VFX/Flocking/Clients": "حركة الأسراب (عملاء)",
  "VFX/Flocking/Fields": "حركة الأسراب (حقول)",
  "VFX/Interactive": "تأثيرات تفاعلية",

  "_Intern/Editor_Helper": "مساعد المحرر",
};
