/**
 * Display-only Arabic labels for real folder paths found in Risen 1 archives
 * (verified against a real 2680-file templates-full.pak). Keyed by the exact
 * full path (not just the leaf name) since the same leaf name can appear
 * under different parents. Purely cosmetic — never used for file operations,
 * selection, or the archive's own paths.
 *
 * Deeply-nested developer/test folders with no clear meaning (e.g. names of
 * individual developers under NPC/Test/Testkram_Thorsten) are intentionally
 * left untranslated rather than guessed.
 */
export const RISEN_FOLDER_NAMES_AR: Record<string, string> = {
  Items: "الأغراض",
  "Items/Amulets": "التمائم",
  "Items/AnimalTrophies": "جوائز الصيد",
  "Items/Armor": "الدروع",
  "Items/Carryable": "أغراض قابلة للحمل",
  "Items/Container": "الحاويات",
  "Items/Food": "الطعام",
  "Items/Helmets": "الخوذات",
  "Items/Keys": "المفاتيح",
  "Items/Magic": "السحر",
  "Items/MagicOrbs": "الكرات السحرية",
  "Items/Minerals": "المعادن",
  "Items/Plants": "النباتات",
  "Items/Potions": "الجرعات",
  "Items/Quests": "أغراض المهام",
  "Items/Quests/Titan_Armor_Set": "طقم درع العملاق",
  "Items/Recipes_Alchemy": "وصفات الخيمياء",
  "Items/Recipes_Cooking": "وصفات الطبخ",
  "Items/Recipes_Trophy": "وصفات الجوائز",
  "Items/Rings": "الخواتم",
  "Items/Runes": "الأحجار الرونية",
  "Items/Scrolls": "اللفافات",
  "Items/Shields": "الدروع الواقية",
  "Items/Smithing_broken": "مواد حدادة معطوبة",
  "Items/Smithing_raw": "مواد حدادة خام",
  "Items/Teleports": "بوابات الانتقال",
  "Items/Tools": "الأدوات",
  "Items/Valueable": "أغراض قيّمة",
  "Items/Weapons_Axes": "الفؤوس",
  "Items/Weapons_Bows": "الأقواس",
  "Items/Weapons_Crossbows": "الأقواس المعترضة",
  "Items/Weapons_Staffs": "العصي السحرية",
  "Items/Weapons_Swords": "السيوف",
  "Items/Weapons_System": "نظام الأسلحة",
  "Items/Written": "مواد مكتوبة",
  "Items/z_DailyRoutines": "روتين يومي (اختبار)",

  Lights: "الإضاءة",
  "Lights/DungeonLights": "إضاءة الأقبية",

  Monster: "الوحوش",
  "Monster/Ambient": "وحوش محيطية",
  "Monster/Kapitel 1": "الفصل 1 (وحوش)",
  "Monster/Kapitel 2": "الفصل 2 (وحوش)",
  "Monster/Kapitel 3": "الفصل 3 (وحوش)",
  "Monster/Kapitel 4": "الفصل 4 (وحوش)",
  "Monster/Monster_Heads": "رؤوس الوحوش",
  "Monster/Special": "وحوش خاصة",

  NPC: "الشخصيات",
  "NPC/Don": "شخصيات الدون",
  "NPC/Harbour": "شخصيات الميناء",
  "NPC/Monastery": "شخصيات الدير",
  "NPC/Test": "اختبار (شخصيات)",
  "NPC/World": "شخصيات العالم",
  "NPC/World_Dead": "شخصيات ميتة",
  "NPC/_HumanParts": "أجزاء جسم بشرية",
  "NPC/_HumanParts/Head": "الرأس",

  Navigation: "الملاحة",
  "Navigation/AI_Helpers": "مساعدات الذكاء الاصطناعي",
  "Navigation/Anchors": "نقاط الإرساء",
  "Navigation/AreaZones": "مناطق المساحة",
  "Navigation/CollisionCircles": "دوائر التصادم",
  "Navigation/Freepoints": "نقاط حرة",
  "Navigation/Freepoints/Story_FPs": "نقاط حرة (القصة)",
  "Navigation/NavZones": "مناطق الملاحة",
  "Navigation/Startpoints": "نقاط الانطلاق",

  Objects: "الكائنات",
  "Objects/Events": "أحداث",
  "Objects/Events/Story_Events": "أحداث القصة",
  "Objects/Interacts": "تفاعلات",
  "Objects/Interacts/Interacts_Story": "تفاعلات القصة",
  "Objects/Special": "كائنات خاصة",
  "Objects/Speedtree": "أشجار (Speedtree)",
  "Objects/TriggerScriptZones": "مناطق تفعيل سكربتية",
  "Objects/_Architecture": "عناصر معمارية",
  "Objects/_Architecture/SpecialStuff": "عناصر معمارية خاصة",
  "Objects/_MultiTemplates": "قوالب متعددة",

  SFX: "المؤثرات الصوتية",
  "SFX/Ambient": "أصوات محيطية",
  "SFX/Entity": "أصوات الكيانات",
  "SFX/Events": "أصوات الأحداث",

  VFX: "التأثيرات البصرية",
  "VFX/Billboards": "لوحات عرض مسطّحة",
  "VFX/Decals": "ملصقات سطحية",
  "VFX/EffectTest": "اختبار تأثيرات",
  "VFX/Emitter": "باعثات الجسيمات",
  "VFX/Events": "تأثيرات الأحداث",
  "VFX/WaterEmitter": "باعث تأثيرات الماء",

  _Intern: "ملفات داخلية",
  "_Intern/BossFight": "قتال زعيم",
  "_Intern/Essentials": "ملفات أساسية",
  "_Intern/Messages": "رسائل",
};
