project_id = "vyqsempkqpkooeurlmgh"

[functions.proofread-bundled]
verify_jwt = false

[functions.translation-tools]
verify_jwt = false

[functions.translation-analysis]
verify_jwt = false

[functions.enhance-translations]
verify_jwt = false