import pw from '/opt/node22/lib/node_modules/playwright/index.js';
const { chromium } = pw;
const FD = "/tmp/claude-0/-home-user-zelda-arabic-magic-a76daea1/30195602-0f97-5db6-98d0-4ccab372886b/scratchpad/inazuma/fontfiles_ar";
const SHOTS = "/tmp/claude-0/-home-user-zelda-arabic-magic-a76daea1/30195602-0f97-5db6-98d0-4ccab372886b/scratchpad/inazuma/shots";
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await browser.newContext({ viewport: { width: 1500, height: 1000 } }).then(c=>c.newPage());
page.on('pageerror', e => console.log('PAGEERROR:', String(e).slice(0,300)));
await page.goto('file:///home/user/zelda-arabic-magic-a76daea1/tools/inazuma-font-editor.html');
await page.setInputFiles('#file', [`${FD}/FONT12.NFTR`,`${FD}/FONT12N.NFTR`,`${FD}/FONT8.NFTR`]);
await page.waitForTimeout(1200);
await page.click('#btnVerify'); await page.waitForTimeout(500);
console.log('verify:', await page.textContent('#toast'));
await page.click('#tabEdit'); await page.waitForTimeout(1500);
console.log('editTitle:', await page.textContent('#editTitle'));
console.log('audit:', (await page.textContent('#audit')).slice(0,180));
await page.screenshot({ path: `${SHOTS}/patched_edit.png` });
await page.click('#tabTest'); await page.waitForTimeout(1500);
console.log('testStat:', await page.textContent('#testStat'));
await page.screenshot({ path: `${SHOTS}/patched_test.png` });
await browser.close();
console.log('OK');
