/**
 * The Arabic glyphs Pokémon Ruby Destiny draws, and where they go.
 *
 * The font lives at 0xEA2C40 and gives every code a 64-byte cell: 8 pixels
 * wide, 16 tall, 4 bits a pixel, four bytes a row. Colour 15 is the body and
 * 14 the shadow, one pixel right and below — the same build as the game's own
 * Latin letters. That address was found by zeroing regions of the ROM and
 * watching the main menu in an emulator until "Start" and "Option" stopped
 * printing; an earlier candidate at 0xEAAB80 turned out to be dead data that
 * nothing reads.
 *
 * The glyphs are held in codepoint order and placed in whichever code the
 * encoder assigned to that codepoint — see pkm-metrics.ts, which hands the
 * codes out by how far they advance so a wide letter does not end up in a
 * narrow code and lose its last columns under the next one.
 *
 * The glyphs themselves are not rasterised from a TTF. At 8x13 a typeface's
 * strokes are thinner than a pixel, and the rounding drops whichever ones it
 * likes — the stem of ك, the bowl of ف — leaving letters that look torn. These
 * come from the Mother 3 fan translation, whose Arabic was drawn by hand on the
 * pixel grid, carried across 1bpp to 4bpp and seated on this game's baseline.
 * Eighteen forms Mother 3 does not supply (ص ض ط ظ ع in some positions, and
 * ء آ ؛) are drawn here in the same style; twelve of those had entries in the
 * Mother 3 table pointing into a second font that is not shipped, which is why
 * ص first came out as a small circle.
 */

import { PKM_SLOT_COUNT, pkmArabicSlots, pkmFontSlots } from "./pkm-charmap";

/** Where the font starts in the ROM. */
export const PKM_FONT_OFFSET = 0xea2c40;
/** Bytes per glyph: 8x16 pixels at 4 bits each. */
export const PKM_GLYPH_BYTES = 64;

/** 129 glyphs for codes 0x01..0x81, in slot order. */
export const PKM_ARABIC_GLYPHS_B64 =
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwDgAA7wAAAP8OAADuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7wAAAA4AAADvAAAA7wAA8A4AAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw7wAA7/4OAO/gAAD+DgAA4O8AAADvAAAA7wAAAO8AAAAOAAAA7wAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8OAPDu7wDg7w4A8P8OAODuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8O8AAO8OAAD+7wAA7w4AAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/DgAA7gAAAO8AAADvAAAA7wAAAO8AAADvAAAA/g4AAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/w4AAO4AAADvAAAA7wAAAO8AAADvAAAA7wAAAP7////g7u7uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPDvAADvDgAA/u8AAO8OAAD+DgAA8A4AAPAOAADwDgAA8A4AAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw7wAA7w4AAP7vAAD/DgAA/g4AAPAOAADwDgAA8P///+Du7u4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8O8AAO8OAAD+7wAA7w4AAA7/DgDw7u8A8A7vAOD/7wAA7u8AAADvAO/wDgD+7wAA4A4AAAAAAAAAAAAAAAAAAPDvAADvDgAA/u8AAO8OAAAO/w4A8O7vAPAO7wDg////AO7v7gAA7wDv8A4A/u8AAOAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAOAADwDgAA8A4AAPAOAADwDgAA8A4AAOAAAADw7wAA7w4AAP7vAADvDgAAAAAAAAAAAAAAAAAAAAAAAAAAAADvAAAA7wAAAO8AAADvAAAA7wAAAP7////g7u7u8O8AAO8OAAD+7wAA7w4AAAAAAAAAAAAAAAAAAPDvAADvDgAA/u8AAO8O/w4O8O7v8P4ODu/g/w7vAP4O/v/vAODuDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8O8AAO8OAAD+7wAA7w4AAA4A/w7w/u7v7/AO/+/g7+7+/w4A4O4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/DgDw7gAA4P8OAPDuAADg8A4AAPAOAP/vAADuDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw7wAA7w4AAP7vAADvDgAADu8AAADvAAD//v//7uDu7gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO8AAADvAAAA7wAAAO8AAADvAAAA7wAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvAAAA7wAAAO8AAADvAAAA7wAAAP7////g7u7uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7wDwDu8A8A7+/+8A4O4OAADvAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO8A8A7vAPAO/v/v/+DuDu4A7wAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8A4AAPAOAP/vAADuDgAAAO8AAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO8AAADvAAD//v//7uDu7gDvAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO/vAAAODgAA8O8AAO/+DgDv8A4A/u8AAOAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO/vAAAODgAAAO8AAPDvAADv7wAA/+8AAO7///8A7u7uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPD+DgDg4AAA7wDwDu8A8A7+/+8A4O4OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw/g4A4OAAAO8A8A7vAPAO/v/v/+DuDu4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P4OAODgAAAA8A4AAPAOAP/vAADuDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPD+DgDg4AAAAO8AAADvAAD//v//7uDu7gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO8AAAAOAADw/g4A4OAAAO8A8A7vAPAO/v/vAODuDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvAAAADgAA8P4OAODgAADvAPAO7wDwDv7/7//g7g7uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7wAAAA4AAPD+DgDg4AAAAPAOAADwDgD/7wAA7g4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO8AAAAOAADw/g4A4OAAAADvAAAA7wAA//7//+7g7u4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8OAO7+7wAA7w4A8A4AAO/wDgDv4AAA/v/vAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/7wAA7v7vAAD/DgDw7v//7wDu7u/wDgDv4AAA/v8OAODuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8O8AAOD+DgAA4O8A//8OAO7uAAAA7wAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPDvAADg/g4AAODvAP/////u7u7uAO8AAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//DgDu/u8AAO8OAPAOAADvAAAA7wAAAP7/7wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+8AAO7+7wAA/w4A8O7//+8A7u7vAAAA/v8OAODuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPDvAADg/g4AAODvAP//DgDu7gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw7wAA4P4OAADg7wD/////7u7u7gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO8AAAAOAAD//w4A7v7vAADvDgDwDgAA7wAAAO8AAAD+/+8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA7wAAAA4AAP/vAADu/u8AAP8OAPDu///vAO7u7wAAAP7/DgDg7gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAOAADgAADw7wAA4P4OAADg7wD//w4A7u4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwDgAA4AAA8O8AAOD+DgAA4O8A/////+7u7u4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPDvAADg/g4AAPAOAP//DgDu7gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw7wAA4P4OAADwDgD/////7u7u7gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvAAAADgAA8O8AAOD+DgAA8A4A//8OAO7uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7wAAAA4AAPDvAADg/g4AAPAOAP/////u7u7uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvAAAA/g4AAPAOAADwDgDv7wAA/g4AAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7wAAAP7//wDw7u4A8A4A7+8AAP4OAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvAAAADgAAAO8AAAD+DgAA8A4AAPAOAO/vAAD+DgAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7wAAAA4AAADvAAAA/v//APDu7gDwDgDv7wAA/g4AAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8ADw/v7w/v7+7/Dv7+/wDg7+7wAA4A4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAA8P7+8P7+/u/w7+/v8A4O/u8AAOAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAO8P7+DvD+/g7v7+8ADg4OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwDvD+/g7w/v4O7+/v/w4ODu4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7wAAAA4AAPD+DgDg4PAA8P7+8P7+/u/w7+/v8A4O/u8AAOAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO8AAAAOAADw/g4A4ODwAPD+/vD+/v7v8O/v7/AODv7vAADgDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO8AAAAOAADw/g4A4ODwDvD+/g7w/v4O7+/vAA4ODgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvAAAADgAA8P4OAODg8A7w/v4O8P7+Du/v7/8ODg7uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvAADw/gAA7/Dw/v/v7/DuDu/wDgD+7wAA4A4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7wAA8P4AAO/w8P7//+/w7u7v8A4A/u8AAOAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO8AAPD+AADv8P///+/u7u4OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvAADw/gAA7/D/////7u7u7gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO8AAAAOAAAA7wAA8P4AAO/w8P7/7+/w7g7v8A4A/u8AAOAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvAAAADgAAAO8AAPD+AADv8PD+///v8O7u7/AOAP7vAADgDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7wAAAA4AAADvAADw/gAA7/D////v7u7uDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO8AAAAOAAAA7wAA8P4AAO/w/////+7u7u4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAOAADwDgAA8A4AAPD+7wDw7/4O8A7wDv//7wDu7g4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwDgAA8A4AAPAOAADw/u8A8O/+DvAO8A7//+/v7u4ODgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8A4AAPAOAADwDgAA8P7vAPDv/g7wDvAO///vAO7uDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAOAADwDgAA8A4AAPD+7wDw7/4O8A7wDv//7+/u7g4OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwDgAA8P4OAPDuAADw/u8A8O/+DvAO8A7//+8A7u4OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8A4AAPD+DgDw7gAA8P7vAPDv/g7wDvAO///v/+7uDu4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAOAADw/g4A8O4AAPD+7wDw7/4O8A7wDv//7wDu7g4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwDgAA8P4OAPDuAADw/u8A8O/+DvAO8A7//+/v7u4ODgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///vAP7+DgDg7wAA8P8OAO/uAADvAAAA/v8OAODuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////+/u7u4O8AAPD////v7u7u7wAAAP7/DgDg7gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/w4A8O7vAPAODgD//+8A7u4OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8OAPDu7wDwDg4A/////+7u7u4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7wAAAA4AAAD/DgDw7u8A8A4OAOD/DgDw7gAA7wAAAO8A7wD+/w4A4O4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO8AAAAOAAD//////v7u7uDvAADw////7+7u7u8AAAD+/w4A4O4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvAAAADgAAAP8OAPDu7wDwDg4A///vAO7uDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvAAAADgAAAAAAAP/////+/u7u4O8AAP/+///u4O7uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO8AAAAOAAAA/w4A8P4O8O7/Du8A/g7vAPAO/v/vAODuDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvAAAADgAAAP8OAPD+DvDu/w7vAP4O7wDw//7/7+7g7g4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvAAAADgAAAP8OAPD+DgDg/w4AAP4OAP/vAADuDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7wAAAA4AAAD/DgDw/g4A4P8OAAD+DgD/7///7g7u7gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPD+DgDg4AAAAP8OAPD+DvDu/w7vAP4O7wDwDv7/7wDg7g4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw/g4A4OAAAAD/DgDw/g7w7v8O7wD+Du8A8P/+/+/u4O4OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw/g4A4OAAAAD/DgDw/g4A4P8OAAD+DgD/7wAA7g4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P4OAODgAAAA/w4A8P4OAOD/DgAA/g4A/+///+4O7u4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw7+8A7w7vAP7v7wDvDu/vDgDv7wAA7/7//w7g7u4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8O/vAO8O7wD+7+8A7w7v7w4A7+8AAO/+///+4O7u4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPDvAADvDgDwDgAA4O8AAAD+DgAA4O8A//8OAO7uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw7wAA7w4A8A4AAODvAAAA/g4AAODvAP///v/u7uDuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvAAAA7wAAAO8A8A7vAO8A7wDvAO8A/v8OAODuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7wAAAO8AAADvAPAO7wDvAO8A7wD///7/7u7g7gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7wAAAO8AAADvAAAA7wAAAO8AAP8OAADuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO8AAADvAAAA7wAAAO8AAADvAAD//v//7uDu7gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8OAPDu7wDwDu8A7/8OAO/uAADvAAAA7wAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/DgDw7u8A8A7vAO///v/v7uDu7wAAAO8AAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPDvAADv/g7/7/AO7v7vAADgDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw7wAA7/4O/+/w/+7+7+4A4A4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvAADvDu8A7wDvAO8A7wD+/w4A4O4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7wAA7w7vAO8A7wDvAP///v/u7uDuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8A4AAOAAAADwDgAA8A4A/+8AAO4OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO8AAAAOAAAA7wAAAO8AAP/+///u4O7uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7+8AAA4OAADw7wAA7/4OAO/wDgD+7wAA4A4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7wAA8O8AAO/vAAD/7wAA7v///wDu7u4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8O8AAO/+Dv/+/g7u7+8AAP7vAADgDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPDvAADv/g7//v7/7v/v7gDuDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8OAPDu7wDwDu8A4P/vAADu7wAAAO8AAPAOAP/vAADuDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/DgDw7u8A8A7vAOD///8A7u/uAADvAADwDgD/7wAA7g4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8O8P7u7+/wDg7v4O8A7wD+Dv7/7wDg7g4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/w7w/u7v7/AO/+/g7+7vAP4O/v/vAODuDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/w7w/u7v7/AODu/g7wDvAP4O/v/vAODuDgDw/g4A4OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/DvD+7u/v8A7/7+Dv7u8A/g7+/+8A4O4OAPD+DgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwDgAA8A4A/+8AAO4OAADw/g4A4OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7wAAAO8AAP/+///u4O7u8P4OAODgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvAAD/DgAA7gDvAPAO7wDwDu8A8A7vAPAO7wDg7+8A//8OAO7uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7wAA/w4AAO4A7wDwDu8A8A7vAPAO7wDwDu8A4O//Dv//7gDu7gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8O8AAPAOAAD/7wAA7g7vAPAO7wDwDu8A8A7vAPAO7wDg7+8A///vAO7uDgAAAAAAAAAAAAAAAAAAAAAAAAAAAPDvAADwDgAA/+/vAO4O7wDwDu8A8A7vAPAO7wDg7/8O///uAO7uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAO7wDwDu8A8A7vAPAO7wDg7+8A//8OAO7uAAAA/w4A8O4AAOD/DgDw7gAAAAAAAAAAAAAAAAAAAAAAAAAAAADwDu8A8A7vAPAO7wDwDu8A4O/vAP///g7u7uAAAP8OAPDuAADg/w4A8O4AAAAAAAAAAAAAAAAAAAAAAAAAAAAA8A7vAPAO7wDwDu8A8A7vAODv7wD//w4A7u4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAO7wDwDu8A8A7vAPAO7wDg7+8A///+Du7u4AAAAAAAAAAAAAAAAAAAAAAA";

function decodeGlyphs(): Uint8Array {
  const bin = atob(PKM_ARABIC_GLYPHS_B64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

/**
 * Writes the Arabic glyphs into a copy of the ROM.
 *
 * Only the kana slots are touched, so every Latin letter, digit and symbol the
 * game draws elsewhere survives untouched.
 */
export function applyPkmArabicFont(rom: Uint8Array): Uint8Array {
  const glyphs = decodeGlyphs();
  const expected = PKM_SLOT_COUNT * PKM_GLYPH_BYTES;
  if (glyphs.length !== expected) {
    throw new Error(`الخط العربي حجمه ${glyphs.length} بايت والمتوقّع ${expected}`);
  }
  const all = pkmArabicSlots();
  const last = PKM_FONT_OFFSET + (all[all.length - 1] + 1) * PKM_GLYPH_BYTES;
  if (last > rom.length) {
    throw new Error("الملف أصغر من أن يحوي خط اللعبة — هل هذا روم Ruby Destiny؟");
  }
  // Glyph by glyph rather than one block, and to the code the encoder gives it
  // — the codes are handed out by width now, not in order, so the `i`-th glyph
  // does not belong to the `i`-th code. (The run also has a hole in it at `é`,
  // whose cell the game still draws inside every POKéMON not yet translated.)
  const out = new Uint8Array(rom);
  pkmFontSlots().forEach((slot, i) => {
    out.set(glyphs.subarray(i * PKM_GLYPH_BYTES, (i + 1) * PKM_GLYPH_BYTES), PKM_FONT_OFFSET + slot * PKM_GLYPH_BYTES);
  });
  return out;
}

/** True when a ROM already carries the Arabic glyphs. */
export function hasPkmArabicFont(rom: Uint8Array): boolean {
  const glyphs = decodeGlyphs();
  const slots = pkmFontSlots();
  const all = pkmArabicSlots();
  const last = PKM_FONT_OFFSET + (all[all.length - 1] + 1) * PKM_GLYPH_BYTES;
  if (last > rom.length) return false;
  return slots.every((slot, i) => {
    const at = PKM_FONT_OFFSET + slot * PKM_GLYPH_BYTES;
    for (let k = 0; k < PKM_GLYPH_BYTES; k++) {
      if (rom[at + k] !== glyphs[i * PKM_GLYPH_BYTES + k]) return false;
    }
    return true;
  });
}
