/**
 * Arabic glyphs for Inazuma Eleven's NFTR fonts, rescaled from the real
 * hand-drawn dialogue-font art (font_message, sub-file 1) in the Pokémon
 * Platinum Arabic project's own font narc -- the font the user's friend
 * drew for that project, not the Emerald/Ruby-Destiny-shared placeholder
 * previously used here. Extracted at glyph_index = charmap_code - 1 against
 * pokeplatinum's own tools/msgenc/charmap.txt Arabic presentation-form
 * section, then rescaled to Inazuma's cell shapes.
 *
 * Slots are Shift-JIS hiragana codes 0x829F-0x82F1 -- 83 of them, all dead in
 * an English-only ROM -- so no CMAP block is touched, only the glyph bitmap
 * and width already stored at that existing index. 83 is the hard ceiling
 * of this trick, and Arabic shaping (arabic-processing.ts's ARABIC_FORMS +
 * LAM_ALEF_LIGATURES) can produce more distinct presentation forms than that,
 * so this list is a prioritized subset rather than full coverage: every
 * positional form (isolated/final/initial/medial) for the 16 most frequent
 * letters, the 4 lam-alef ligatures, then isolated (+ final where the budget
 * allowed) forms for the next 12 letters, then isolated-only for hamza-on-alef,
 * ta marbuta and alef maqsura. A codepoint outside this set is left as-is by
 * encodeInazumaArabicText and reported in `missing` rather than dropped.
 */
export const INAZUMA_ARABIC_CODEPOINTS: number[] = [0xFE8D, 0xFE8E, 0xFEDD, 0xFEDE, 0xFEDF, 0xFEE0, 0xFEF1, 0xFEF2, 0xFEF3, 0xFEF4, 0xFEE1, 0xFEE2, 0xFEE3, 0xFEE4, 0xFEED, 0xFEEE, 0xFEE5, 0xFEE6, 0xFEE7, 0xFEE8, 0xFEE9, 0xFEEA, 0xFEEB, 0xFEEC, 0xFE8F, 0xFE90, 0xFE91, 0xFE92, 0xFE95, 0xFE96, 0xFE97, 0xFE98, 0xFEAD, 0xFEAE, 0xFEC9, 0xFECA, 0xFECB, 0xFECC, 0xFEB1, 0xFEB2, 0xFEB3, 0xFEB4, 0xFED5, 0xFED6, 0xFED7, 0xFED8, 0xFED1, 0xFED2, 0xFED3, 0xFED4, 0xFEA9, 0xFEAA, 0xFED9, 0xFEDA, 0xFEDB, 0xFEDC, 0xFEF5, 0xFEF6, 0xFEF7, 0xFEF8, 0xFEF9, 0xFEFA, 0xFEFB, 0xFEFC, 0xFEA1, 0xFE9D, 0xFEB5, 0xFEB9, 0xFEC1, 0xFEA5, 0xFEAB, 0xFEBD, 0xFE99, 0xFEAF, 0xFECD, 0xFEC5, 0xFE83, 0xFE93, 0xFEEF, 0xFEA2, 0xFE9E, 0xFEB6, 0xFEBA];

/** 11x12, 1bpp, 17 bytes/glyph -- FONT12.NFTR and FONT12N.NFTR share this shape. */
export const INAZUMA_FONT12_GLYPHS_B64 = "AAAAAAQAgBACAEAAAAAAAAAAAAAABACAEA4BwAAAAAAAAAAAAAAQAgBQCwFgPAAAAAAAAAAAABACAFAbA2A8AAAAAAAAAAAADAGAMAcAYAAAAAAAAAAAAAAMAYAwDwHgAAAAAAAAAAAAAAAGAfAPA2B8BwDgAAAAAAAAAAAAwD8H4GwHAOAcAAAAAAAAAAAwBwBgHAAAAAAAAAAAAAAAADAPAeA4AAAAAAAAAAAAAAAAcAoB4DwBgDAAAAAAAAAAAABwCgPgfAGAMAAAAAAAAAAAAHALAeA4AAAAAAAAAAAAAAAAcBsD4DgAAAAAAAAAAAAAA4BwDgHAIAeAcAAAAAAAAAADgHAeA8AgB4BwAAAAAAAAAAGAeAsB4DgAAAAAAAAAAAAAAYB4GwPgOAAAAAAAAAAAAAwBgDAHAGAAAAAAAAAAAAAADAGAMA8B4AAAAAAAAAAAAAAAAYB4DwDAAAAAAAAAAAAAAAwBgDgPAcAAAAAAAAAAAAAAAAMA8B8D4DgAAAAAAAAAAAAAAwDwPwfgOAAAAAAAAAAAAAAAAFgPAcAYAAAAAAAAAAAAAAAAWB8DwBgAAAAAAAAAAAAAAAAwBwBgCAAAAAAAAAAAAAAAADAPAeAYAAAAAAAAAAAAHAOAWA8BwAAAAAAAAAAAAAAcA4BYHwPAAAAAAAAAAAAAAA4BwDAHAGAAAAAAAAAAAAAAHAOAMA8B4AAAAAAAAAAAAAAAAAAADgGAMAOAIAAAAAAAAAAAAAAOAYAwA4AgAAAAAAAAAAOAcA4BwAwHgOAAAAAAAAAcA8B4HgPgDAeA4AAAAAAAAAADgHAPAeAAAAAAAAAAAAAAHAPAeB8D4AAAAAAAAAAAAAAACAHgPwfgPAAAAAAAAAAAAAAIAeA/D+E8AAAAAAAAAAAAAAYA8B8B4AAAAAAAAAAAAAAABgDwPwfgAAAAAAAAAAABwDAHAPAbA+A4AAAAAAAAAAHAMAcA8DsH4DgAAAAAAAAAAOAcA4BwDwDgAAAAAAAAAAAA4BwDgHAPAeAAAAAAAAAAAACAMAcA8BsD4DgAAAAAAAAAAYAwBwDwOwfgOAAAAAAAAAAAYBwDgHAPAOAAAAAAAAAAAABgHAOAcA8B4AAAAAAAAAAAAAAAAYBwDwHgAAAAAAAAAAAAAAABgHAPAeAAAAAAAAAAAAMAfA+B+D8DwAAAAAAAAAAAAwB8D4H4PwfAAAAAAAAAAAABwAwBgHAPAeAAAAAAAAAAAAHADAGAcD8H4AAAAAAAADAHAGAUAoBQDwHgAAAAAAAAOAcA4BQCgFAfA+AAAAAAAAA4BwDgFAKAUA8B4AAAAAAAADgHACAUAoBQHwPgAAAAAAAAAAAAABQCgFAPAeA4BwDgBAAAAAAAFAKAUB8D4DgHAOAEAAAAAAAUAoBQDwHgAAAAAAAAAAAAABQCgFAfA+AAAAAAAAAAAAAAAAAAeA4AwAwHgOAAAAAAAAAAAAB4DgDAPAeA4AAAAAwBgHAIAeA/B+A8AAAAAAAAAAAAAAwBwH4P4DwDAAAAAAAAACAEA4DwHwHgAAAAAAAAAAAAAAwBgHgOAMAMB4DgAAAAAAAADAGAcA8B4AAAAAAAAAAAAABgDAHAfg/gPAMAAAAAAAAAYBwDgFgPAcAAAAAAAAAAAAAAAAGAMA4BgDADgCAAAAAAAAAMA4BwDgHADAWA8BwAAAAAIBQDgPAfAeAAAAAAAAAcA4BwBACAEAIAQAAAAAAAAAAAAAAcAYB4DwDAAAAAAAAAAAAAAAAGAfAPA2B8AAAAAAAAAAAAAAHAeB4DYAwHAAAAAAAAAAAAAcB4HgNgPAeA4AAAAAwBgHAIAeA/D+E8AAAAAAAAAAAAAAwBwH4f4zwDAAAAAA==";
export const INAZUMA_FONT12_WIDTHS: number[] = [6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 11, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 11, 7, 7, 7, 11, 7, 7, 7, 7, 7, 7, 7, 7, 7, 11, 11];

/** 7x8, 1bpp, 7 bytes/glyph -- FONT8.NFTR. */
export const INAZUMA_FONT8_GLYPHS_B64 = "AADBgwAAAAAAwYcAAAAAAQOFDgAAAAEDjQ4AAAAAgQMAAAAAAIEHAAAAAAAHhx4YAAAABg8aHDgAAAEDBgAAAAABBw4AAAAAAwcOBAAAAAMHHgQAAAADBwwAAAAAAw8MAAAAAAOHCBwAAAADjwgcAAAAA4UOAAAAAAONDgAAAACBAwAAAAAAgQcAAAAAAAOHAAAAAACBhwAAAAAABw8MAAAAAAcPDAAAAAAChwQAAAAAAo8EAAAAAAEDBgAAAAABBwQAAAABwocAAAAAAcKPAAAAAADBAwAAAAABwQcAAAAAAAAGDAwAAAAABgwMAAAAA4cGHAAAAcOPAhwAAAADhwAAAAABw48AAAAAAAcPDgAAAAAHDy4AAAAAB48AAAAAAAePAAAAAcMHjQ4AAAHDB40OAAAA4YOHAAAAAOGDhwAAAACDB40OAAABgweNDgAAAEGDhwAAAABBg4cAAAAAAAOHAAAAAAADhwAAAAEDh48AAAABA4ePAAAAAcDDBwAAAAHAww8AAABgQcOHAAAAYMHDjwAAAGDBw4cAAABgYcOPAAAAAAHDhwwcGAABw48MHBgAAcOHAAAAAAHDjwAAAAAAA4YGHAAAAAOGDhwAAYMHDw4AAAAABh8uDAAAYMePAAAAAACDhgYcAAAAg4cAAAAAAgYfLgwAAEHChwAAAAAAAQYMDAAAAIOHBhQ4AGHHjwAAADBgwYMAAAAAAcOHAAAAAAAHhx4AAAAAA48CHAAAAAOPDhwAAYMHDy4AAAAABh8uDAA=";
export const INAZUMA_FONT8_WIDTHS: number[] = [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 7, 5, 5, 5, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 7, 7];
