/**
 * The Arabic forms Mother 3's main font does not supply, drawn to match it.
 *
 * Twelve forms in Mother 3's table point at codes 0xA0 and above, and that
 * range of the font holds the game's own symbols — arrows, Greek letters, PK.
 * Taken at face value they render as a small circle or a diagonal line, which
 * is how صديقي lost its first letter on screen when this was first tried in
 * Pokémon. Seven more forms have no entry at all.
 *
 * Rather than invent a style, each is derived from a form that does exist in
 * that font, so the weight and the seat on the baseline match the rest:
 *
 *   ص  the isolated form exists; the final adds the joining pixel on the
 *      right, the initial drops the tail and runs the base to the left edge.
 *   ض  ص plus the dot.
 *   ط  the final ظ exists; ط is the same letter without its dot.
 *   ظ  the initial and medial come off that same final.
 *   ع  the initial and final exist; the medial adds a joining pixel.
 *   آ  the final exists; the isolated drops its joining pixel.
 *   ء  stands alone in every position, so one drawing serves all four.
 *
 * The pictures are 8 columns wide and seated the way Mother 3 seats its own
 * Arabic — the top row of the drawing is the top of the font's ink band, so
 * they line up with the shipped forms without any fitting.
 */

/** One drawn form: rows of `#` for ink, `.` for blank, 8 columns wide. */
export interface DrawnForm {
  rows: boolean[][];
  width: number;
}

const SAD_INI = `
........
........
........
........
......#.
.....#.#
....#..#
#######.
`;

const SAD_MED = `
........
........
........
........
......#.
.....#.#
....#..#
########
`;

const SAD_FIN = `
........
........
........
........
......#.
.....#.#
....#..#
.#.#####
#..#....
#..#....
.##.....
`;

const TAH_FIN = `
........
.#......
.#......
.#......
.#.##...
.##..#..
.#...#..
#####.#.
`;

const TAH_ISO = `
........
.#......
.#......
.#......
.#.##...
.##..#..
.#...#..
#####...
`;

const ZAH_ISO = `
........
.#......
.#.#....
.#......
.#.##...
.##..#..
.#...#..
#####...
`;

const ZAH_MED = `
........
.#......
.#.#....
.#......
.#.##...
.##..#..
.#...#..
#####.#.
`;

const AIN_ISO = `
........
........
........
........
#####...
.#.#....
..#.....
.###....
#.......
#.......
.###....
`;

const AIN_MED = `
........
........
........
........
..##....
.#..#...
.#......
########
`;

const ALEF_MADDA_ISO = `
##......
........
#.......
#.......
#.......
#.......
#.......
.#......
`;

const HAMZA = `
........
........
........
..##....
.#..#...
..#.....
.###....
........
`;

const SEMICOLON = `
........
........
........
........
..#.....
........
..#.....
..#.....
.#......
`;

const CELL_WIDTH = 8;
const CELL_HEIGHT = 16;

function parse(art: string): boolean[][] {
  const rows: boolean[][] = Array.from({ length: CELL_HEIGHT }, () =>
    new Array<boolean>(CELL_WIDTH).fill(false)
  );
  art.trim().split("\n").forEach((line, y) => {
    if (y >= CELL_HEIGHT) return;
    for (let x = 0; x < CELL_WIDTH && x < line.length; x++) rows[y][x] = line[x] === "#";
  });
  return rows;
}

/** ض is ص with the dot over the loop. */
function withDot(rows: boolean[][]): boolean[][] {
  const out = rows.map((r) => [...r]);
  out[2][6] = true;
  return out;
}

function form(rows: boolean[][]): DrawnForm {
  let width = 1;
  for (const row of rows) {
    for (let x = 0; x < row.length; x++) if (row[x]) width = Math.max(width, x + 1);
  }
  return { rows, width };
}

const sadIni = parse(SAD_INI);
const sadMed = parse(SAD_MED);
const sadFin = parse(SAD_FIN);
const tahIso = parse(TAH_ISO);
const tahFin = parse(TAH_FIN);
const zahIso = parse(ZAH_ISO);

/**
 * Forms drawn here, by their Unicode presentation code.
 *
 * ص isolated comes from the shipped font, and ض isolated is built from it at
 * load time, so neither is listed.
 */
export const M3_DRAWN_FORMS: Record<number, DrawnForm> = {
  0xfeba: form(sadFin), // ـص
  0xfebb: form(sadIni), // صـ
  0xfebc: form(sadMed), // ـصـ
  0xfebe: form(withDot(sadFin)), // ـض
  0xfebf: form(withDot(sadIni)), // ضـ
  0xfec0: form(withDot(sadMed)), // ـضـ
  0xfec1: form(tahIso), // ط
  0xfec2: form(tahFin), // ـط
  0xfec3: form(tahIso), // طـ — its base already reaches the left edge
  0xfec4: form(tahFin), // ـطـ
  0xfec5: form(zahIso), // ظ
  0xfec7: form(zahIso), // ظـ
  0xfec8: form(parse(ZAH_MED)), // ـظـ
  0xfec9: form(parse(AIN_ISO)), // ع
  0xfecc: form(parse(AIN_MED)), // ـعـ
  0xfe81: form(parse(ALEF_MADDA_ISO)), // آ
  0x0621: form(parse(HAMZA)), // ء
  0x061b: form(parse(SEMICOLON)), // ؛
};
