"""The tables the DS engine needs to shape Arabic while it draws.

Same idea as the Emerald one, and for the same reason: text that the game
assembles at run time -- a name the player typed, a species substituted into a
sentence -- meets its neighbours only at print time, so the joining has to be
decided there rather than baked into the stored string.

What differs is the width of a character. Platinum's codes are sixteen bits
and the glyph index is the code itself, so the forms table holds u16 and the
reverse lookup spans the range the Arabic actually occupies rather than a byte.
"""
import os, re, sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "..", "pokeemerald-arabic", "scripts"))
from arshape import FORMS, LIGATURES

PLAT = "/home/user/decomps/pokeplatinum/"
CHARMAP = PLAT + "tools/msgenc/charmap.txt"
OUT = PLAT + "include/arabic_shaping.h"
ARABIC = lambda cp: 0x0600 <= cp <= 0x06FF or 0xFB50 <= cp <= 0xFEFF


def main():
    code = {}
    for line in open(CHARMAP, encoding="utf-8"):
        line = line.split("//")[0].strip()
        m = re.match(r"^([0-9A-Fa-f]{4})=(.)$", line)
        if m and ARABIC(ord(m.group(2))):
            code[ord(m.group(2))] = int(m.group(1), 16)
    assert len(code) == 129, len(code)

    bases = sorted(FORMS)
    idx = {cp: i for i, cp in enumerate(bases)}
    top = max(code.values()) + 1

    base_of = [0xFF] * top
    forms = []
    for cp in bases:
        forms.append([code.get(f, 0) if f else 0 for f in FORMS[cp]])
        for f in FORMS[cp]:
            if f and f in code:
                base_of[code[f]] = idx[cp]

    # A lam-alef glyph is two letters in one; reading it back to the alef would
    # lose the lam. It gets a base of its own: something may join into it, it
    # never joins forward.
    lig_base = len(bases)
    lig, lig_of = [], [0xFF] * top
    for i, alef in enumerate((0x0622, 0x0623, 0x0625, 0x0627)):
        iso, fin = LIGATURES[alef]
        lig.append((idx[alef], code.get(iso, 0), code.get(fin, 0)))
        for f in (iso, fin):
            if f in code:
                base_of[code[f]] = lig_base
                lig_of[code[f]] = i

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Generated by pokeplatinum-arabic/scripts/gen_shaping.py -- do not edit.\n"
                "//\n"
                "// Which base letter a character code draws, and which code draws each of\n"
                "// that letter's four joining forms. A form that does not exist is 0, and a\n"
                "// letter with no initial form never joins to what follows it.\n\n"
                "#ifndef POKEPLATINUM_ARABIC_SHAPING_H\n"
                "#define POKEPLATINUM_ARABIC_SHAPING_H\n\n"
                "#define ARABIC_NO_BASE 0xFF\n"
                "#define ARABIC_FORM_ISOLATED 0\n"
                "#define ARABIC_FORM_FINAL    1\n"
                "#define ARABIC_FORM_INITIAL  2\n"
                "#define ARABIC_FORM_MEDIAL   3\n\n")
        f.write(f"#define ARABIC_BASE_COUNT {len(bases)}\n")
        f.write(f"#define ARABIC_BASE_LAM {idx[0x0644]}\n")
        f.write(f"#define ARABIC_BASE_LIGATURE {lig_base}\n")
        f.write(f"#define ARABIC_CODE_MAX {top}\n\n")
        f.write("static const u8 sArabicBaseOf[ARABIC_CODE_MAX] = {\n")
        for r in range(0, top, 16):
            f.write("    " + ", ".join(f"0x{b:02X}" for b in base_of[r:r + 16]) + ",\n")
        f.write("};\n\n")
        f.write("static const u16 sArabicForms[ARABIC_BASE_COUNT][4] = {\n")
        for cp, row in zip(bases, forms):
            f.write("    { " + ", ".join(f"0x{c:04X}" for c in row) + f" }}, // U+{cp:04X}\n")
        f.write("};\n\n")
        f.write("// lam followed by one of these alefs is drawn as a single ligature\n")
        f.write("static const u16 sArabicLamAlef[][3] = {\n")
        for b, iso, fin in lig:
            f.write(f"    {{ {b}, 0x{iso:04X}, 0x{fin:04X} }},\n")
        f.write("};\n\n")
        f.write("static const u8 sArabicLigatureOf[ARABIC_CODE_MAX] = {\n")
        for r in range(0, top, 16):
            f.write("    " + ", ".join(f"0x{b:02X}" for b in lig_of[r:r + 16]) + ",\n")
        f.write("};\n\n#endif // POKEPLATINUM_ARABIC_SHAPING_H\n")
    print(f"كُتب {OUT}: {len(bases)} حرفاً أساسياً و{len(lig)} ليغاتورة، والمدى حتى 0x{top:04X}")


if __name__ == "__main__":
    main()
