"""The tables the engine needs to shape Arabic while it draws.

Text merged from the tool is already shaped, but anything the game assembles
while it runs is not: a name the player typed, or a name substituted into a
sentence, meets its neighbours only at print time. Shaping there costs a small
table and makes every one of those seams join.

Each entry is read back to its base letter first, so a line that was already
shaped comes out unchanged and one that was not gets fixed.
"""
import re, sys
sys.path.insert(0, ".")
from arshape import FORMS, LIGATURES

SRC = "/home/user/decomps/pokeemerald/"
OUT = SRC + "src/data/arabic_shaping.h"

code = {}
for line in open(SRC + "charmap.txt", encoding="utf-8"):
    m = re.match(r"^'(.)'\s*=\s*([0-9A-F]{2})\s*$", line.split("@")[0].strip())
    if m:
        code.setdefault(ord(m.group(1)), int(m.group(2), 16))

bases = sorted(FORMS)
idx = {cp: i for i, cp in enumerate(bases)}
forms = []
for cp in bases:
    row = []
    for f in FORMS[cp]:
        row.append(code.get(f, 0) if f else 0)
    forms.append(row)

base_of = [0xFF] * 256
for cp, quad in FORMS.items():
    for f in quad:
        if f and f in code:
            base_of[code[f]] = idx[cp]

# A lam-alef glyph is two letters in one and must not be read back to the alef
# alone -- that loses the lam. It gets its own base instead: something may join
# into it, it never joins forward, and it is drawn from its own pair of forms.
LIG_BASE = len(bases)
lig = []
lig_of = [0xFF] * 256
for i, alef in enumerate((0x0622, 0x0623, 0x0625, 0x0627)):
    iso, fin = LIGATURES[alef]
    lig.append((idx[alef], code.get(iso, 0), code.get(fin, 0)))
    for f in (iso, fin):
        if f in code:
            base_of[code[f]] = LIG_BASE
            lig_of[code[f]] = i

with open(OUT, "w", encoding="utf-8") as f:
    f.write("""// Generated by pokeemerald-arabic/scripts/gen_shaping.py -- do not edit.
//
// Which base letter a byte draws, and which byte draws each of that letter's
// four joining forms. A form that does not exist is 0, and a letter with no
// initial form is one that never joins to what follows it.

#define ARABIC_NO_BASE 0xFF
#define ARABIC_FORM_ISOLATED 0
#define ARABIC_FORM_FINAL    1
#define ARABIC_FORM_INITIAL  2
#define ARABIC_FORM_MEDIAL   3

""")
    f.write(f"#define ARABIC_BASE_COUNT {len(bases)}\n")
    f.write(f"#define ARABIC_BASE_LAM {idx[0x0644]}\n")
    f.write(f"#define ARABIC_BASE_LIGATURE {LIG_BASE}\n\n")
    f.write("static const u8 sArabicBaseOf[256] =\n{\n")
    for r in range(16):
        f.write("    " + ", ".join(f"0x{b:02X}" for b in base_of[r*16:(r+1)*16]) + ",\n")
    f.write("};\n\n")
    f.write("static const u8 sArabicForms[ARABIC_BASE_COUNT][4] =\n{\n")
    for cp, row in zip(bases, forms):
        f.write("    { " + ", ".join(f"0x{c:02X}" for c in row) + f" }}, // U+{cp:04X}\n")
    f.write("};\n\n")
    f.write("// lam followed by one of these alefs is drawn as a single ligature\n")
    f.write("static const u8 sArabicLamAlef[][3] =\n{\n")
    for b, iso, fin in lig:
        f.write(f"    {{ {b}, 0x{iso:02X}, 0x{fin:02X} }},\n")
    f.write("};\n\n")
    f.write("// which lam-alef pair a ligature glyph is, so it keeps its own form\n")
    f.write("static const u8 sArabicLigatureOf[256] =\n{\n")
    for r in range(16):
        f.write("    " + ", ".join(f"0x{b:02X}" for b in lig_of[r*16:(r+1)*16]) + ",\n")
    f.write("};\n")
print(f"wrote {OUT}: {len(bases)} base letters, {len(lig)} ligatures")
